"""
Add academic_year_id to GradingSchema

Revision ID: 7a35f7b40ebf
Revises: 8cae22d4c8f9
Create Date: 2026-02-18 22:45:53.828244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a35f7b40ebf'
down_revision = '8cae22d4c8f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grading_schemas', sa.Column('academic_year_id', sa.UUID(), nullable=True))
    op.create_unique_constraint('uq_grading_schema_tenant_ay_name', 'grading_schemas', ['tenant_id', 'academic_year_id', 'name'])
    op.create_foreign_key(None, 'grading_schemas', 'academic_years', ['academic_year_id'], ['id'])
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.create_index('idx_users_tenant_type', 'users', ['tenant_id', 'type'], unique=False)
    op.create_index('idx_users_tenant_login', 'users', ['tenant_id', 'last_login'], unique=False)
    op.create_index('idx_users_tenant_active', 'users', ['tenant_id', 'is_active'], unique=False)
    op.drop_index(op.f('ix_timetables_section_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_grade_id'), table_name='timetables')
    op.drop_constraint(None, 'tenant_notification_configs', type_='foreignkey')
    op.create_index('ix_teachers_employee_id', 'teachers', ['employee_id'], unique=False)
    op.create_index('idx_teachers_status', 'teachers', ['status'], unique=False)
    op.create_index('idx_subjects_tenant', 'subjects', ['tenant_id'], unique=False)
    op.create_index('ix_students_admission_number', 'students', ['admission_number'], unique=False)
    op.create_index('idx_students_status', 'students', ['status'], unique=False)
    op.drop_constraint(None, 'semesters', type_='foreignkey')
    op.drop_index(op.f('ix_semesters_tenant_id'), table_name='semesters')
    op.alter_column('semesters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('semesters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_schedules_lookup', table_name='schedules')
    op.create_index('ix_remedial_sessions_tenant_enrollment', 'remedial_sessions', ['tenant_id', 'enrollment_id'], unique=False)
    op.create_unique_constraint('uq_promotion_status_tenant_enrollment', 'promotion_status', ['tenant_id', 'enrollment_id'])
    op.create_index('ix_promotion_status_tenant_student', 'promotion_status', ['tenant_id', 'student_id'], unique=False)
    op.create_unique_constraint('uq_promotion_criteria_tenant_year_grade', 'promotion_criteria', ['tenant_id', 'academic_year_id', 'grade_id'])
    op.create_index('ix_promotion_criteria_tenant_grade', 'promotion_criteria', ['tenant_id', 'grade_id'], unique=False)
    op.drop_constraint(None, 'periods', type_='foreignkey')
    op.drop_index(op.f('ix_periods_tenant_id'), table_name='periods')
    op.alter_column('periods', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('periods', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'grading_schemas', type_='foreignkey')
    op.drop_constraint('uq_grading_schema_tenant_ay_name', 'grading_schemas', type_='unique')
    op.drop_column('grading_schemas', 'academic_year_id')
    op.create_index('ix_grades_student_subject', 'grades', ['tenant_id', 'student_id', 'subject_id'], unique=False)
    op.create_index('ix_grades_assessment_lookup', 'grades', ['tenant_id', 'assessment_id', 'assessment_type'], unique=False)
    op.create_index('idx_grades_tenant_id_student_id', 'grades', ['tenant_id', 'student_id'], unique=False)
    op.create_index('idx_grades_student_id', 'grades', ['student_id'], unique=False)
    op.create_index('idx_grades_assessment_type', 'grades', ['assessment_type'], unique=False)
    op.create_index('idx_grades_assessment_id', 'grades', ['assessment_id'], unique=False)
    op.alter_column('grades', 'graded_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('grades', 'subject_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('exams', 'academic_year_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_enrollments_tenant_grade_active', 'enrollments', ['tenant_id', 'grade_id', 'is_active'], unique=False)
    op.create_index('ix_enrollments_student_id', 'enrollments', ['student_id'], unique=False)
    op.create_index('ix_enrollments_section_id', 'enrollments', ['section_id'], unique=False)
    op.create_index('ix_enrollments_grade_id', 'enrollments', ['grade_id'], unique=False)
    op.create_index('ix_enrollments_academic_year_id', 'enrollments', ['academic_year_id'], unique=False)
    op.create_index('idx_enrollments_section_lookup', 'enrollments', ['tenant_id', 'academic_year_id', 'section_id', 'is_active', 'status'], unique=False)
    op.create_index('idx_enrollments_perf_lookup', 'enrollments', ['tenant_id', 'academic_year_id', 'grade_id', 'is_active', 'status'], unique=False)
    op.drop_constraint('unique_class_identity', 'classes', type_='unique')
    op.drop_index(op.f('ix_classes_academic_year_id'), table_name='classes')
    op.drop_index('idx_classes_tenant_ay_grade', table_name='classes')
    op.create_index('idx_classes_tenant_active', 'classes', ['tenant_id', 'is_active'], unique=False)
    op.alter_column('classes', 'academic_year_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'class_subjects', type_='foreignkey')
    op.drop_index(op.f('ix_class_subjects_tenant_id'), table_name='class_subjects')
    op.alter_column('class_subjects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('class_subjects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'class_enrollments', type_='foreignkey')
    op.create_index('idx_class_enrollments_student_id', 'class_enrollments', ['student_id'], unique=False)
    op.create_index('idx_class_enrollments_class_id', 'class_enrollments', ['class_id'], unique=False)
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.create_index('ix_assignments_tenant_subject', 'assignments', ['tenant_id', 'subject_id'], unique=False)
    op.alter_column('assignments', 'academic_year_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_table('submissions',
    sa.Column('assignment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'GRADED', 'RETURNED', name='submissionstatus'), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attachment_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name='submissions_assignment_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='submissions_student_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='submissions_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='submissions_pkey')
    )
    op.create_index('ix_submissions_tenant_id', 'submissions', ['tenant_id'], unique=False)
    op.create_index('ix_submissions_tenant_assignment', 'submissions', ['tenant_id', 'assignment_id'], unique=False)
    op.create_index('ix_submissions_assignment_student', 'submissions', ['assignment_id', 'student_id'], unique=False)
    op.create_table('teacher_subject_assignments',
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('grade_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('section_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('academic_year', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('room', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['academic_grades.id'], name='teacher_subject_assignments_grade_id_fkey'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name='teacher_subject_assignments_section_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='teacher_subject_assignments_subject_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='teacher_subject_assignments_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='teacher_subject_assignments_pkey'),
    sa.UniqueConstraint('tenant_id', 'grade_id', 'section_id', 'subject_id', 'academic_year', name='uq_teacher_subject_assign')
    )
    op.create_index('ix_teacher_subject_assignments_tenant_id', 'teacher_subject_assignments', ['tenant_id'], unique=False)
    op.create_index('ix_teacher_subject_assignments_academic_year', 'teacher_subject_assignments', ['academic_year'], unique=False)
    # ### end Alembic commands ###